name: Publish healthcheck docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: coldstack-network/blockchain_rpc_healthcheck
  context: ./deploy/rpc_healthcheck/

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1.0,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
